### ISSUE TITLE
Multiple finalizers in wrapCompile causes segfault 

### ISSUE THREAD

**Issue by neongreen** [ChrisKuklewicz/regex-tdfa#10]
I think this bug was reported by @owst, but not sure.

https://sourceforge.net/p/lazy-regex/bugs/2/

> wrapCompile in Text.Regex.Posix.Wrap uses mallocForeignPtrBytes to create a foreign pointer (which implicitly assigns a finalizer), but also explicitly assigns a finalizer via addForeignPtrFinalizer, causing a double-free to occur, leading to an occasional segfault. Removing the line "addForeignPtrFinalizer c_regfree regex_fptr" fixes the problem.

**Comment by jberryman** [comment]
I don't see `mallocForeignPtrBytes` in the codebase so this should probably be closed right?

**Comment by neongreen** [comment]
Makes sense.
