### ISSUE TITLE
parseRegex calling error ?

### ISSUE THREAD

**Issue by simonmichael** [ChrisKuklewicz/regex-tdfa#18]
Thanks for regex-tdfa, which hledger has been using for a long time.

Are we seeing a regex-tdfa bug at https://github.com/simonmichael/hledger/issues/889#issuecomment-427622883 ? parseRegex appears to be calling error, when we would rather see Left "lookahead syntax not supported" or simply for the regex to be interpreted without error according to what regex-tdfa does support.

**Comment by neongreen** [comment]
Well, `parseRegex` does return an error message:

```
> parseRegex "(?!tax)"
Left "(?!tax)" (line 1, column 2):
unexpected "?"
expecting empty () or anchor ^ or $ or an atom
```

The error you're seeing probably comes from `makeRegexOpts`:

```haskell
unwrap :: Either String v -> v
unwrap x = case x of Left msg -> err ("Text.Regex.TDFA.String died: "++msg)
                     Right v -> v

compile  :: CompOption -- ^ Flags (summed together)
         -> ExecOption -- ^ Flags (summed together)
         -> String     -- ^ The regular expression to compile (ASCII only, no null bytes)
         -> Either String Regex -- ^ Returns: the compiled regular expression
compile compOpt execOpt source =
  case parseRegex source of
    Left msg -> Left ("parseRegex for Text.Regex.TDFA.String failed:"++show msg)
    Right pattern -> Right (patternToRegex pattern compOpt execOpt)

instance RegexMaker Regex CompOption ExecOption String where
  makeRegexOpts c e source = unwrap (compile c e source)
  makeRegexOptsM c e source = either fail return $ compile c e source
```

You can get an `Either` instead (or whatever other instance of `MonadFail`) by switching to `makeRegexOptsM`.

> when we would rather see Left "lookahead syntax not supported"

I will merge a PR if you make one, but I will not implement this by myself :( It's not my codebase, so the only thing I do is keep it alive (because it's pretty widely used).

**Comment by simonmichael** [comment]
Fair enough. Thanks for the explanation. For the record, would you agree that this library calling error is a bug ?

**Comment by neongreen** [comment]
I'm not sure I would, given that there is another function in the library which does the same thing but doesn't call `error`. It's like saying that the existence of `fromJust` is a bug.

**Comment by simonmichael** [comment]
I see your point. Ideally for library users http://hackage.haskell.org/package/regex-base-0.93.2/docs/Text-Regex-Base-RegexLike.html#t:RegexMaker would say clearly "If there is an error in processing, then error will be called.", as http://hackage.haskell.org/package/regex-tdfa-1.2.3.1/docs/Text-Regex-TDFA.html#v:-61--126- does. Perhaps I'll take it up with them.

**Comment by neongreen** [comment]
No, fixing documentation is always welcome. I'll do it.

**Comment by simonmichael** [comment]
Great! Thanks.

**Comment by neongreen** [comment]
Oh, apparently this method is defined in `regex-base` and so the docs should be there. @ChrisKuklewicz what do you think about moving `regex-base` to Github as well?

**Comment by neongreen** [comment]
The `regex-*` ecosystem now lives at https://github.com/haskell-hvr, PRs are welcome there.
