### ISSUE TITLE
Consider using package enummapset

### ISSUE THREAD

**Issue by Mikolaj** [ChrisKuklewicz/regex-tdfa#19]
Hi! I you feel like refactoring and sharing the maintaining effort, then `EnumMap` and `EnumSet' is also defined in package https://hackage.haskell.org/package/enummapset

You are welcome to use it and add anything that is missing (though almost all of what containers define is there already). I use the package and I'm the maintainer currently, so there is hope it will be kept up to date with GHC version. Also, I'd gladly give co-maintainer status to you to share the burden and reduce the bus factor. Cheers!

**Comment by neongreen** [comment]
I'm not sure about this one.

`regex-tdfa` is a rather widely used package (see its [reverse deps](http://packdeps.haskellers.com/reverse/regex-tdfa)). I would rather avoid incurring additional dependencies like `witherable`, `these` and `semigroupoids`. At the same time I don't want to put you in the position where you have to make some kind of implicit or explicit commitment to _not_ do things like https://github.com/Mikolaj/enummapset/issues/14.

**Comment by Mikolaj** [comment]
I'd rather be a package with commitments than without users. :D

Seriously, we can write this commitment into the .cabal description of the package and keep to it. In the worst case we quarrel, split the package and you keep your lean version and have 2 packages to maintain, with clearly separated concerns. I guess the question is rather do you value the separation of concerns in this case high enough to justify the hassle. E.g., one of the functions in your implementation somehow tweaks the behaviour of IntMaps in an error case, which is an example both of non-separated concerns and of the effort needed to refactor now and keep from using such convenient hacks in the future.

**Comment by neongreen** [comment]
> E.g., one of the functions in your implementation somehow tweaks the behaviour of IntMaps in an error case

Hm, where?

> keep from using such convenient hacks in the future

Well, I do see value in keeping people (including myself) from using convenient hacks 🙂

**Comment by neongreen** [comment]
Oh, and by the way: we have both `EnumMap` and `CharMap`. Do you think your `EnumMap` will have the same performance as our `CharMap`, or should I benchmark that?

**Comment by Mikolaj** [comment]
I've found the hack:

https://github.com/ChrisKuklewicz/regex-tdfa/blob/ef3978c50372b7a5390d550f0f639fd59261e3fa/Data/IntMap/EnumMap2.hs#L53

It may be the only one, but the files need a careful once-over.

Regarding `CharMap`, the only way I could match your hand-crafted version would be with a newtype around `Char`, with the custom fast `toEnum`, but then you'd need to use that newtype instead of `Char` in at least a layer of operations that directly access  `CharMap`, or create such layer to isolate your API from the newtype (I guess, you already isolate API from  `CharMap`, but that's one step further). Probably the benefits are not worth it.

The offending extra `isTrue# (int2Word# i# `leWord#` 0x10FFFF##)`, with some luck, is just a single CPU instruction operating on a value that is already in a register. If so, it's basically free, because CPUs spend ages idling and waiting for memory anyway. But it's a hopeful theory, so benchmarks are a good idea (just define `unsafeChr = chr` and see what happens).

**Comment by neongreen** [comment]
Actually, the lookup thing is very weird – `maybe (fail "EnumMap.lookup failed") return $ M.lookup (fromEnum k) m` is equivalent to `M.lookup (fromEnum k) m` 🤔

**Comment by neongreen** [comment]
(I'm not the author of this code, I'm just maintaining it, so I don't know why `lookup` is like it is.)

**Comment by Mikolaj** [comment]
Oh, you are right, it's the monad's `fail`, not a custom `error` operation. Heh, so it's mostly harmless. :)

**Comment by neongreen** [comment]
Meanwhile: https://github.com/ChrisKuklewicz/regex-tdfa/pull/20.

The tests pass but I haven't benchmarked yet. My budget for maintaining regex-tdfa is fairly small, so if you want to contribute a small benchmark suite, that would be very appreciated.

**Comment by Mikolaj** [comment]
Frankly, I don't even know the API, though I work with code that uses https://github.com/iconnect/regex that uses `regex-tdfa`. Perhaps the benchmarks from `regex` (which I don't know either) could be scavenged or just used as is?

BTW, I've had a very quick look at the PR and if, in fact, there is a slowdown, you could try using https://hackage.haskell.org/package/enummapset-0.6.0.1/docs/Data-EnumMap-Lazy.html#v:enumMapToIntMap in a place that proves problematic, to go down to `IntMap` and there manually use `unsafeChr` as needed. If that's just one place, that's still cleaner than a separate `CharMap`.

Also, I'm wondering, would using the `EnumMap.Strict` be any faster or less memory consuming that the current use of  `EnumMap.Lazy` (the type is the same, so they can even be mixed and matched)? I guess this package predates the appearance of `IntMap.Strict`...

**Comment by neongreen** [comment]
It looks like `regex` doesn't have benchmarks either :/

> enumMapToIntMap

Oh, nice to know that this one exists.

> Also, I'm wondering, would using the EnumMap.Strict be any faster or less memory consuming that the current use of EnumMap.Lazy (the type is the same, so they can even be mixed and matched)?

Yeah, it might.

**Comment by Mikolaj** [comment]
Yes, I misread, you are completely right, there no benchmarks and @cdornan confirms he has no benchmarks of his own and would gladly use TDFA and PCRE benchmarks if the respective maintainers create any and add them to their repos. I wonder if there's any standard set of benchmarks on the net. Then adding `benchmark` stanzas to the cabal file should not be a big deal. I have no clue about regexps, though. :)

**Comment by neongreen** [comment]
I am handing over the maintanership, please make a PR to https://github.com/haskell-hvr/regex-tdfa if you want this discussed or merged.

**Comment by Mikolaj** [comment]
Will do. Thank you very much for your service to the community!
