### ISSUE TITLE
dash in range not correctly parsed

### ISSUE THREAD

**Issue by pjljvandelaar** [ChrisKuklewicz/regex-tdfa#24]
As specified in 
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html
```
the expression "[--@]" matches any of the characters between '-' and '@' inclusive
```
However, `("@" =~ "[--@]")` results in
```
Explict error in module Text.Regex.TDFA.String : 
Text.Regex.TDFA.String died: parseRegex for Text.Regex.TDFA.String failed:"[--@]" (line 1, column 4):
       unexpected A dash is in the wrong place in a bracket
       expecting "]"
       CallStack (from HasCallStack):
         error, called at .\Text\Regex\TDFA\Common.hs:29:3 in regex-tdfa-1.2.3.1-DVMXTrvIFHgDCky8s203W0:Text.Regex.TDFA.Common)
```

**Comment by pjljvandelaar** [comment]
Note the typo in https://github.com/ChrisKuklewicz/regex-tdfa/blob/343b49f2bbae13a7f7b6da08ab410f2f6b42f578/Text/Regex/TDFA/Common.hs#L29
Explic**i**t

**Comment by neongreen** [comment]
Agreed, this is a bug. I'm merely keeping this package on life support but I will certainly accept a PR that fixes this bug.

**Comment by neongreen** [comment]
Moving over to https://github.com/haskell-hvr/regex-tdfa/issues/1.
