### ISSUE TITLE
Won't build with GHC 9.2 because -XNoMonoPatBinds was removed

### ISSUE THREAD

**Issue by cdsmith** [ChrisKuklewicz/regex-tdfa#30]
Even with `cabal build --allow-newer`, cabal will not build regex-tdfa using GHC 9.2.  The reason is that it specifies `-XNoMonoPatBinds` as a default extension in the cabal file.  This has had no effect since GHC 7.4, and has finally been removed in GHC 9.2.

**Comment by neongreen** [comment]
The regex-* family has a new maintainer now, please report at https://github.com/haskell-hvr/regex-tdfa.

**Comment by cdsmith** [comment]
Done, thanks.  https://github.com/haskell-hvr/regex-tdfa/issues/23
