### ISSUE TITLE
Regular expression substitution?

### ISSUE THREAD

**Issue by jml** [ChrisKuklewicz/regex-tdfa#4]
Would it be possible to have a substitution function for replacing substrings using regular expressions?

The regex-compat library has `[subRegex](http://hackage.haskell.org/package/regex-compat-0.92/docs/Text-Regex.html)`, which does this, but it operates on Text.Regex.Posix `Regex` values.

I'm not certain, but I *think* this could be done as part of regex-base.

**Comment by jml** [comment]
I found http://stackoverflow.com/a/3928438/463800, where @ChrisKuklewicz says that doing a generic one that's performant is too hard. I don't think that excludes providing replace functions for `String` and `ByteString` here.

**Comment by neongreen** [comment]
I am handing over the maintainership, please open an issue at https://github.com/haskell-hvr/regex-tdfa or https://github.com/haskell-hvr/regex-base.
