### ISSUE TITLE
Support for Text?

### ISSUE THREAD

**Issue by bgamari** [ChrisKuklewicz/regex-tdfa#5]
It would be great to merge the [regex-tdfa-text](https://hackage.haskell.org/package/regex-tdfa-text) package.

**Comment by neongreen** [comment]
@bgamari Do you remember why your regex-tdfa-text patches weren't accepted in the first place?

**Comment by bgamari** [comment]
They weren't my patches. Regardless, I have no idea why they weren't accepted. I suspect they just appeared after maintenance of the package tapered off, but I could be wrong.

**Comment by neongreen** [comment]
> They weren't my patches.

Oh, sorry, I confused the nicks.

> I suspect they just appeared after maintenance of the package tapered off, but I could be wrong.

The thing is that when I looked at regex-tdfa-text (a year ago), I _think_ I saw a discussion of some problems with it, so I'm not sure. Anyway, I'll research it.

**Comment by asr** [comment]
I also think it would be great to merge the `regex-tdfa-text` package (for example, right now, `regex-tdfa` supports GHC 8.8.1 but `regex-tdfa-text` doesn't).

Blocking https://github.com/agda/agda/issues/3725.

**Comment by neongreen** [comment]
I will accept a PR that merges `regex-tdfa-text` (e.g. from https://github.com/hackage-trustees/regex-tdfa-text) into this package and makes sure that the tests in `test/` are ran on `Text.Regex.TDFA.Text` in addition to `Text.Regex.TDFA`.

**Comment by asr** [comment]
From [regex-tdfa-text](http://hackage.haskell.org/package/regex-tdfa-text):

> This should be part of regex-tdfa package. But my patches are not accepted yet. So, I made a separate package. If you are interested in my patches, see http://hub.darcs.net/shelarcy/regex-base and http://hub.darcs.net/shelarcy/regex-tdfa.

By browsing in http://hub.darcs.net/shelarcy/regex-tdfa, we can find the change [Add text support](https://hub.darcs.net/shelarcy/regex-tdfa/patch/c6beb710403dc3b037504c761195c91c76015e5a). Maybe it is easier to prepare the PR from this change.

**Comment by neongreen** [comment]
Moving over to https://github.com/haskell-hvr/regex-tdfa/issues/4.
