### ISSUE TITLE
Crash on windows for simple substitution 

### ISSUE THREAD

**Issue by neongreen** [ChrisKuklewicz/regex-tdfa#8]
https://sourceforge.net/p/lazy-regex/bugs/6/

> The folllowing code crashes when run on windows
>
> ``` haskell
> module Main where
> 
> import qualified Text.Regex as Re -- from regex-compat
> import Debug.Trace
> 
> main :: IO ()
> main = do
>   putStr $ cleanWord "jan"
>   putStr $ cleanWord "dec"
>   putStr $ cleanWord "jun" -- crashes here
> 
> cleanWord :: String -> String
> cleanWord word_ =
>   let word = trace (show word_) word_ in
>   let re = Re.mkRegexWithOpts "(jun|jul|aug|sep|oct|nov|dec)" True False in
>   Re.subRegex re word ""
> ```
> 
> It crashes when it gets to the "jun" text. If I move the jun alt to the end of the list then it works fine
> 
> I created a SO question while trying to work this out
> http://stackoverflow.com/questions/39047317/simple-regular-expression-substitution-crashes-on-windows-using-regex-compat/39101634#39101634
> 
> Feedback from there was the following
> 
> > It's a bug, probably in regex-posix, due to its difference in the inclusion of the underlying BSD regex library from 1994. In sslow, an invalid memory address (-1(%rdx) with rdx = 0) will be accessed.

**Comment by jberryman** [comment]
I'm confused about all of these sourceforge bugs here. They seem to be for different libraries altogether. Is the idea to remember to test regex-tdfa against them to ensure it doesn't suffer from the same bug?

**Comment by neongreen** [comment]
@jberryman I believe that these sourceforge bugs are for this library, just for a very old version of it. The sourceforge page I took the bugs from used to be the homepage for this library:

<img src="https://user-images.githubusercontent.com/1523306/31865871-d3304c68-b77e-11e7-89a0-90fdc560eafc.png" width="400px">

**Comment by neongreen** [comment]
Actually, yeah, this one is for regex-posix.
